# Generated by Django 5.2 on 2025-11-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_education_degree_alter_education_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["-end_year", "-start_year"],
                "verbose_name_plural": "Education History",
            },
        ),
        migrations.RemoveField(
            model_name="education",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start_date",
        ),
        migrations.AddField(
            model_name="education",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
