# Generated by Django 5.2 on 2025-11-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "community",
            "0003_alter_education_options_remove_education_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["-end_date", "-start_date"],
                "verbose_name_plural": "Education History",
            },
        ),
        migrations.RemoveField(
            model_name="education",
            name="end_year",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start_year",
        ),
        migrations.AddField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
