# Generated by Django 5.2 on 2025-12-02 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "community",
            "0004_alter_education_options_remove_education_end_year_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="is_current",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="user",
        ),
        migrations.AddField(
            model_name="experience",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experience",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="user_profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience_history",
                to="community.userprofile",
            ),
            preserve_default=False,
        ),
    ]
